FROM node:18-alpine AS base

FROM base AS builder

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY src ./src
COPY public ./public
COPY next.config.js .
COPY tsconfig.json .
COPY tailwind.config.ts .
COPY postcss.config.js .

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL="http://103.30.194.124:3000"
ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

RUN npm run build

FROM base AS runner

WORKDIR /app

RUN npm i sharp

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL="http://103.30.194.124:3000"
ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

ENV PORT=${PORT}

CMD ["node", "server.js"]

LABEL name="web-profile-next-app" \
      version="latest"
