version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: ./docker/next-app/Dockerfile
    image: 
      ${NODE_ENV == 'local' && 'web-profile-next-app'}
      ${NODE_ENV == 'production' && 'harisramadan22/web-profile-next-app:latest'}
    container_name: web-profile-next-app
    ports:
      - "3000:3000"
    networks:
      - web_profile_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image:
      ${NODE_ENV == 'local' && 'web-profile-nginx'}
      ${NODE_ENV == 'production' && 'harisramadan22/web-profile-nginx:latest'}
    container_name: web-profile-nginx
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
    networks:
      - web_profile_network

networks:
  web_profile_network:
    driver: bridge
