version: '3.8'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    # restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - web_profile_network
  
  nginx:
    build: ./nginx
    container_name: nginx
    # restart: unless-stopped
    ports:
      - 80:80
    # depends_on:
    #   - next-app
    networks:
      - web_profile_network
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Add additional NGINX configuration or static files if needed

networks:
  web_profile_network:
    external: true
