version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: ./docker/next-app/Dockerfile
    image: harisramadan22/web-profile-next-app:latest
    container_name: web-profile-next-app
    ports:
      - "3001:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - web_profile_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: harisramadan22/web-profile-nginx:alpine-slim
    container_name: web-profile-nginx
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
    networks:
      - web_profile_network

networks:
  web_profile_network:
    driver: bridge
