version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: ./docker/next-app/Dockerfile
    image: web-profile-next-app
    container_name: web-profile-next-app
    ports:
      - "3000:3000"
    networks:
      - web_profile_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: web-profile-nginx
    container_name: web-profile-nginx
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
    networks:
      - web_profile_network

networks:
  web_profile_network:
    driver: bridge
