version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: ./docker/next-app/Dockerfile
      args:
        - NODE_ENV=production
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    image: web-profile-next-app:latest
    container_name: web-profile-next-app
    ports:
      - ${PORT}:${DOCKER_PORT}
    networks:
      - web_profile_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - PORT=${PORT}
        - HOST=${HOST}
    image: web-profile-nginx:alpine-slim
    container_name: web-profile-nginx
    ports:
      - "80:80"
    networks:
      - web_profile_network

networks:
  web_profile_network:
    driver: bridge
