version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  nginx:
    image: nginx:alpine-slim
    container_name: my-nginx
    restart: always
    ports:
      - 80:80
    networks:
      - my_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Add additional NGINX configuration or static files if needed

networks:
  my_network:
    external: true
